In [4]:
import numpy as np 

# Para x1 
x_1 = np.array([[0.5],[0],[-0.5],[0]])
A_1 = np.array([[1,1],
              [1,0],
              [6,1],
              [1,0]])
# Para x2
x_2 = np.array([[1],[0],[1],[0]])
A_2 = np.array([[1,1],
              [1,0],
              [6,1],
              [1,0]])
# Para x3 
x_3 = np.array([[0.9],[0],[1.1],[0]])
A_3 = np.array([[1,1],
              [1,0],
              [6,1],
              [1,0]])
coefs_1 = np.linalg.pinv(A_1).dot(x_1)
coefs_2 = np.linalg.pinv(A_2).dot(x_2)
coefs_3 = np.linalg.pinv(A_3).dot(x_3)
print("C")
print(coefs_1)
print(coefs_2)
print(coefs_3)



[[-0.17241379]
 [ 0.60344828]]
[[1.38777878e-16]
 [1.00000000e+00]]
[[0.03448276]
 [0.87931034]]
